version: '3.9'

services:

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      - db
    command: gunicorn -b 0.0.0.0:8000 app:create_app --capture-output

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
